
service: ${file(env.configs.yml):feature}

frameworkVersion: ">=1.6.0 <2.1.0"

provider:
  name: aws
  stackName: ${self:custom.featurealias}
  runtime: dotnetcore2.1
  stage: ${file(env.configs.yml):stage}
  region: ${file(env.configs.yml):region}
  accountId: ${file(env.configs.yml):accountId}
  environment:
    DynamoDbConfiguration__TableName: ${file(env.configs.yml):dynamoTable}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DynamoDbConfiguration__TableName}"

package:
  artifact: bin/release/netcoreapp2.1/deploy-package.zip
  
custom:
  featurealias:  ${file(env.configs.yml):feature}-${file(env.configs.yml):environment}

functions:
  create:
    handler: DotNetServerless.Functions::DotNetServerless.Functions.Lambda.CreateItemFunction::Run
    events:
      - http:
          path: todos
          method: post
          cors: true

  get:
    handler: DotNetServerless.Functions::DotNetServerless.Functions.Lambda.GetItemFunction::Run
    events:
      - http:
          path: todos/{id}
          method: get
          cors: true

  update:
    handler: DotNetServerless.Functions::DotNetServerless.Functions.Lambda.UpdateItemFunction::Run
    events:
      - http:
          path: todos/{id}
          method: put
          cors: true

resources:
  Resources:
    TodosDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: Code
            AttributeType: S
          - AttributeName: Id
            AttributeType: S
        KeySchema:
          - AttributeName: Code
            KeyType: HASH
          - AttributeName: Id
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DynamoDbConfiguration__TableName}
        
